import {type NoteData, noteFactory, NoteType, Direction} from './types/index'
import {reactive} from 'vue'


export const songData: NoteData[] = reactive([
    noteFactory('1:0', Direction.Right, NoteType.Tap),
    noteFactory('1:1', Direction.Right, NoteType.Tap),
    noteFactory('1:2', Direction.Right, NoteType.Tap),
    noteFactory('1:3', Direction.Right, NoteType.Tap),
    noteFactory('2:0', Direction.Right, NoteType.Tap),
    noteFactory('2:1', Direction.Right, NoteType.Tap),
    noteFactory('2:2', Direction.Right, NoteType.Tap),
    noteFactory('2:3', Direction.Right, NoteType.Tap),
    noteFactory('3:0', Direction.Right, NoteType.Tap),
    noteFactory('3:1', Direction.Right, NoteType.Tap),
    noteFactory('3:2', Direction.Right, NoteType.Tap),
    noteFactory('3:3', Direction.Right, NoteType.Tap),
    noteFactory('4:0', Direction.Right, NoteType.Tap),
    noteFactory('4:1', Direction.Right, NoteType.Tap),
    noteFactory('4:2', Direction.Right, NoteType.Tap),
    noteFactory('4:3', Direction.Right, NoteType.Tap),
    noteFactory('5:0', Direction.Right, NoteType.Tap),
    noteFactory('5:1', Direction.Right, NoteType.Tap),
    noteFactory('5:2', Direction.Right, NoteType.Tap),
    noteFactory('5:3', Direction.Right, NoteType.Tap),
    noteFactory('6:0', Direction.Right, NoteType.Tap),
    noteFactory('6:1', Direction.Right, NoteType.Tap),
    noteFactory('6:2', Direction.Right, NoteType.Tap),
    noteFactory('6:3', Direction.Right, NoteType.Tap),
    noteFactory('7:0', Direction.Right, NoteType.Tap),
    noteFactory('7:1', Direction.Right, NoteType.Tap),
    noteFactory('7:2', Direction.Right, NoteType.Tap),
    noteFactory('7:3', Direction.Right, NoteType.Tap),
    noteFactory('8:0', Direction.Right, NoteType.Tap),
    noteFactory('8:1', Direction.Right, NoteType.Tap),
    noteFactory('8:2', Direction.Right, NoteType.Tap),
    noteFactory('8:3', Direction.Right, NoteType.Tap),
    noteFactory('9:0', Direction.Right, NoteType.Tap),
    noteFactory('9:1', Direction.Right, NoteType.Tap),
    noteFactory('9:2', Direction.Right, NoteType.Tap),
    noteFactory('9:3', Direction.Right, NoteType.Tap),
    noteFactory('10:0', Direction.Right, NoteType.Tap),
    noteFactory('10:1', Direction.Right, NoteType.Tap),
    noteFactory('10:2', Direction.Right, NoteType.Tap),
    noteFactory('10:3', Direction.Right, NoteType.Tap),
  ])