import { type NoteData, noteFactory, NoteType, Direction } from './types/index'
import { reactive } from 'vue'


export const songData: NoteData[] = reactive([

  noteFactory('0:3', Direction.Right, NoteType.Tap),
  noteFactory('1:3', Direction.Right, NoteType.Tap),
  noteFactory('2:3', Direction.Right, NoteType.Tap),

  noteFactory('3:1:2', Direction.Right, NoteType.Tap),
  noteFactory('3:2:0', Direction.Right, NoteType.Tap),
  noteFactory('3:2:2', Direction.Right, NoteType.Tap),
  noteFactory('3:3:0', Direction.Right, NoteType.Tap),
  noteFactory('3:3:2', Direction.Right, NoteType.Tap),
  noteFactory('4:0:0', Direction.Right, NoteType.Tap),

  noteFactory('4:1:2', Direction.Right, NoteType.Tap),
  noteFactory('4:2:0', Direction.Right, NoteType.Tap),
  noteFactory('4:2:2', Direction.Right, NoteType.Tap),
  noteFactory('4:3:0', Direction.Right, NoteType.Tap),
  noteFactory('4:3:2', Direction.Right, NoteType.Tap),
  noteFactory('5:0:0', Direction.Right, NoteType.Tap),

  noteFactory('5:1:0', Direction.Right, NoteType.Tap),
  noteFactory('5:1:2', Direction.Right, NoteType.Tap),
  noteFactory('5:2:0', Direction.Right, NoteType.Tap),
  noteFactory('5:2:2', Direction.Right, NoteType.Tap),
  noteFactory('5:3:0', Direction.Right, NoteType.Tap),
  noteFactory('5:3:2', Direction.Right, NoteType.Tap),
  noteFactory('6:0:0', Direction.Right, NoteType.Tap),

  noteFactory('7:1:2', Direction.Right, NoteType.Tap),
  noteFactory('7:2:0', Direction.Right, NoteType.Tap),
  noteFactory('7:2:2', Direction.Right, NoteType.Tap),
  noteFactory('7:3:0', Direction.Right, NoteType.Tap),
  noteFactory('7:3:2', Direction.Right, NoteType.Tap),
  noteFactory('8:0:0', Direction.Right, NoteType.Tap),

  noteFactory('8:1:2', Direction.Right, NoteType.Tap),
  noteFactory('8:2:0', Direction.Right, NoteType.Tap),
  noteFactory('8:2:2', Direction.Right, NoteType.Tap),
  noteFactory('8:3:0', Direction.Right, NoteType.Tap),
  noteFactory('8:3:2', Direction.Right, NoteType.Tap),
  noteFactory('9:0:0', Direction.Right, NoteType.Tap),
  
  noteFactory('9:1:0', Direction.Right, NoteType.Tap),
  noteFactory('9:1:2', Direction.Right, NoteType.Tap),
  noteFactory('9:2:0', Direction.Right, NoteType.Tap),
  noteFactory('9:2:2', Direction.Right, NoteType.Tap),
  noteFactory('9:3:0', Direction.Right, NoteType.Tap),
  noteFactory('9:3:2', Direction.Right, NoteType.Tap),
  noteFactory('10:0:0', Direction.Right, NoteType.Tap),


  //pickup the momentum
  noteFactory('11:1:2', Direction.Right, NoteType.Tap),
  noteFactory('11:1:3', Direction.Right, NoteType.Tap),
  noteFactory('11:2:2', Direction.Right, NoteType.Tap),
  noteFactory('11:3:0', Direction.Right, NoteType.Tap),
  noteFactory('11:3:2', Direction.Right, NoteType.Tap),

  noteFactory('12:1:2', Direction.Right, NoteType.Tap),
  noteFactory('12:1:3', Direction.Right, NoteType.Tap),
  noteFactory('12:2:2', Direction.Right, NoteType.Tap),
  noteFactory('12:3:0', Direction.Right, NoteType.Tap),
  noteFactory('12:3:2', Direction.Right, NoteType.Tap),

  noteFactory('13:1:2', Direction.Right, NoteType.Tap),
  noteFactory('13:1:3', Direction.Right, NoteType.Tap),
  noteFactory('13:2:2', Direction.Right, NoteType.Tap),
  noteFactory('13:3:0', Direction.Right, NoteType.Tap),
  noteFactory('13:3:2', Direction.Right, NoteType.Tap),

  noteFactory('14:2:2', Direction.Right, NoteType.Tap),
  noteFactory('14:3:0', Direction.Right, NoteType.Tap),

  noteFactory('15:0:0', Direction.Right, NoteType.Right360),
  noteFactory('15:0:0', Direction.Left, NoteType.Right360),
  noteFactory('15:0:0', Direction.Up, NoteType.Right360),
  noteFactory('15:0:0', Direction.Down, NoteType.Right360),




  // noteFactory('1:0', Direction.Right, NoteType.Tap),
  // noteFactory('1:1', Direction.Right, NoteType.Tap),
  // noteFactory('1:2', Direction.Right, NoteType.Tap),
  // noteFactory('1:3', Direction.Right, NoteType.Tap),
  // noteFactory('2:0', Direction.Right, NoteType.Tap),
  // noteFactory('2:1', Direction.Right, NoteType.Tap),
  // noteFactory('2:2', Direction.Right, NoteType.Tap),
  // noteFactory('2:3', Direction.Right, NoteType.Tap),
  // noteFactory('3:0', Direction.Right, NoteType.Tap),
  // noteFactory('3:1', Direction.Right, NoteType.Tap),
  // noteFactory('3:2', Direction.Right, NoteType.Tap),
  // noteFactory('3:3', Direction.Right, NoteType.Tap),
  // noteFactory('4:0', Direction.Right, NoteType.Tap),
  // noteFactory('4:1', Direction.Right, NoteType.Tap),
  // noteFactory('4:2', Direction.Right, NoteType.Tap),
  // noteFactory('4:3', Direction.Right, NoteType.Tap),
  // noteFactory('5:0', Direction.Right, NoteType.Tap),
  // noteFactory('5:1', Direction.Right, NoteType.Tap),
  // noteFactory('5:2', Direction.Right, NoteType.Tap),
  // noteFactory('5:3', Direction.Right, NoteType.Tap),
  // noteFactory('6:0', Direction.Right, NoteType.Tap),
  // noteFactory('6:1', Direction.Right, NoteType.Tap),
  // noteFactory('6:2', Direction.Right, NoteType.Tap),
  // noteFactory('6:3', Direction.Right, NoteType.Tap),
  // noteFactory('7:0', Direction.Right, NoteType.Tap),
  // noteFactory('7:1', Direction.Right, NoteType.Tap),
  // noteFactory('7:2', Direction.Right, NoteType.Tap),
  // noteFactory('7:3', Direction.Right, NoteType.Tap),
  // noteFactory('8:0', Direction.Right, NoteType.Tap),
  // noteFactory('8:1', Direction.Right, NoteType.Tap),
  // noteFactory('8:2', Direction.Right, NoteType.Tap),
  // noteFactory('8:3', Direction.Right, NoteType.Tap),
  // noteFactory('9:0', Direction.Right, NoteType.Tap),
  // noteFactory('9:1', Direction.Right, NoteType.Tap),
  // noteFactory('9:2', Direction.Right, NoteType.Tap),
  // noteFactory('9:3', Direction.Right, NoteType.Tap),
  // noteFactory('10:0', Direction.Right, NoteType.Tap),
  // noteFactory('10:1', Direction.Right, NoteType.Tap),
  // noteFactory('10:2', Direction.Right, NoteType.Tap),
  // noteFactory('10:3', Direction.Right, NoteType.Tap),
])